package example;

import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import lombok.Value;

/**
 * Immutable entity with the constructor generated by lombok.
 * <p>
 * {@link ImmutableEntity} is immutable due to used {@link Value} annotation,
 * so fields are efficiently final private. The default Jackson serialization model not longer works.
 */
@Value
@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
public class ImmutableEntity {

    String field;

    int severalWordsField;
}
